name: Check Markdown Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # monthly

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Check Markdown Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: "yes"
          folder-path: content
